const cardActionTypes = {
  GET_ALL_CARDS_IN_BOARD_START: "GET_ALL_CARDS_IN_BOARD_START",
  GET_ALL_CARDS_IN_BOARD_SUCCESS: "GET_ALL_CARDS_IN_BOARD_SUCCESS",
  GET_ALL_CARDS_IN_BOARD_FAILURE: "GET_ALL_CARDS_IN_BOARD_FAILURE",

  CREATE_CARD_START: "CREATE_CARD_START",
  CREATE_CARD_SUCCESS: "CREATE_CARD_SUCCESS",
  CREATE_CARD_FAILURE: "CREATE_CARD_FAILURE",

  UPDATE_CARD_WHEN_DROP_START: "UPDATE_CARD_WHEN_DROP_START",
  UPDATE_CARD_WHEN_DROP_SUCCESS: "UPDATE_CARD_WHEN_DROP_SUCCESS",
  UPDATE_CARD_WHEN_DROP_FAILURE: "UPDATE_CARD_WHEN_DROP_FAILURE",

  UPDATE_CARD_WHEN_EDIT_START: "UPDATE_CARD_WHEN_EDIT_START",
  UPDATE_CARD_WHEN_EDIT_SUCCESS: "UPDATE_CARD_WHEN_EDIT_SUCCESS",
  UPDATE_CARD_WHEN_EDIT_FAILURE: "UPDATE_CARD_WHEN_EDIT_FAILURE",

  UPDATE_CARD_WHEN_UPLOADIMAGE_START: "UPDATE_CARD_WHEN_UPLOADIMAGE_START",
  UPDATE_CARD_WHEN_UPLOADIMAGE_SUCCESS: "UPDATE_CARD_WHEN_UPLOADIMAGE_SUCCESS",
  UPDATE_CARD_WHEN_UPLOADIMAGE_FAILURE: "UPDATE_CARD_WHEN_UPLOADIMAGE_FAILURE",

  UPDATE_CARD_WHEN_EDITDESC_START: "UPDATE_CARD_WHEN_EDITDESC_START",
  UPDATE_CARD_WHEN_EDITDESC_SUCCESS: "UPDATE_CARD_WHEN_EDITDESC_SUCCESS",
  UPDATE_CARD_WHEN_EDITDESC_FAILURE: "UPDATE_CARD_WHEN_EDITDESC_FAILURE"
};

export default cardActionTypes;
