const boardActionTypes = {
  GET_SPECIFIC_BOARD_START: "GET_SPECIFIC_BOARD_START",
  GET_SPECIFIC_BOARD_SUCCESS: "GET_SPECIFIC_BOARD_SUCCESS",
  GET_SPECIFIC_BOARD_FAILURE: "GET_SPECIFIC_BOARD_FAILURE"
};

export default boardActionTypes;
