const boardActionTypes = {
  GET_SPECIFIC_BOARD_START: "GET_SPECIFIC_BOARD_START",
  GET_SPECIFIC_BOARD_SUCCESS: "GET_SPECIFIC_BOARD_SUCCESS",
  GET_SPECIFIC_BOARD_FAILURE: "GET_SPECIFIC_BOARD_FAILURE",
  GET_PAGE_BOARD_ID: "GET_PAGE_BOARD_ID"
};

export default boardActionTypes;
