const boardActionTypes = {
  GET_ALL_BOARDS_START: "GET_ALL_BOARDS_START",
  GET_ALL_BOARDS_SUCCESS: "GET_ALL_BOARDS_SUCCESS",
  GET_ALL_BOARDS_FAILURE: "GET_ALL_BOARDS_FAILURE",

  CREATE_BOARD_START: "CREATE_BOARD_START",
  CREATE_BOARD_SUCCESS: "CREATE_BOARD_SUCCESS",
  CREATE_BOARD_FAILURE: "CREATE_BOARD_FAILURE",

  DELETE_BOARD_START: "DELETE_BOARD_START",
  DELETE_BOARD_SUCCESS: "DELETE_BOARD_SUCCESS",
  DELETE_BOARD_FAILURE: "DELETE_BOARD_FAILURE"
};

export default boardActionTypes;
