const listActionTypes = {
  GET_ALL_LISTS_IN_BOARD_START: "GET_ALL_LISTS_IN_BOARD_START",
  GET_ALL_LISTS_IN_BOARD_SUCCESS: "GET_ALL_LISTS_IN_BOARD_SUCCESS",
  GET_ALL_LISTS_IN_BOARD_FAILURE: "GET_ALL_LISTS_IN_BOARD_FAILURE",

  CREATE_LIST_START: "CREATE_LIST_START",
  CREATE_LIST_SUCCESS: "CREATE_LIST_SUCCESS",
  CREATE_LIST_FAILURE: "CREATE_LIST_FAILURE",

  DELETE_LIST_START: "DELETE_LIST_START",
  DELETE_LIST_SUCCESS: "DELETE_LIST_SUCCESS",
  DELETE_LIST_FAILURE: "DELETE_LIST_FAILURE"
};

export default listActionTypes;
