const activitiesActionTypes = {
  GET_ALL_ACTIVITIES_START: "GET_ALL_ACTIVITIES_START",
  GET_ALL_ACTIVITIES_SUCCESS: "GET_ALL_ACTIVITIES_SUCCESS",
  GET_ALL_ACTIVITIES_FAILURE: "GET_ALL_ACTIVITIES_FAILURE",

  CREATE_NEW_ACTIVITY_START: "CREATE_NEW_ACTIVITY_START",
  CREATE_NEW_ACTIVITY_SUCCESS: "CREATE_NEW_ACTIVITY_SUCCESS",
  CREATE_NEW_ACTIVITY_FAILURE: "CREATE_NEW_ACTIVITY_FAILURE"
};

export default activitiesActionTypes;
