const userActionTypes = {
  GET_USER_VIA_TOKEN_START: "GET_USER_VIA_TOKEN_START",
  GET_USER_VIA_TOKEN_SUCCESS: "GET_USER_VIA_TOKEN_SUCCESS",
  GET_USER_VIA_TOKEN_FAILURE: "GET_USER_VIA_TOKEN_FAILURE",

  SIGN_IN_USER_START: "SIGN_IN_USER_START",
  SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
  SIGN_IN_USER_FAILURE: "SIGN_IN_USER_FAILURE",

  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
  SIGN_UP_USER_FAILURE: "SIGN_UP_USER_FAILURE",

  SIGN_OUT_USER: "SIGN_OUT_USER"
};

export default userActionTypes;
