const userActionTypes = {
  GET_USER_VIA_TOKEN_START: "GET_USER_VIA_TOKEN_START",
  GET_USER_VIA_TOKEN_SUCCESS: "GET_USER_VIA_TOKEN_SUCCESS",
  GET_USER_VIA_TOKEN_FAILURE: "GET_USER_VIA_TOKEN_FAILURE"
};

export default userActionTypes;
