const cardActionTypes = {
  GET_ALL_CARDS_IN_BOARD_START: "GET_ALL_CARDS_IN_BOARD_START",
  GET_ALL_CARDS_IN_BOARD_SUCCESS: "GET_ALL_CARDS_IN_BOARD_SUCCESS",
  GET_ALL_CARDS_IN_BOARD_FAILURE: "GET_ALL_CARDS_IN_BOARD_FAILURE",

  CREATE_CARD_START: "CREATE_CARD_START",
  CREATE_CARD_SUCCESS: "CREATE_CARD_SUCCESS",
  CREATE_CARD_FAILURE: "CREATE_CARD_FAILURE"
};

export default cardActionTypes;
